export const ProductData = [
  {
    id: 51,
    title: "half sleeves T shirts",
    description:
      "Many store is creating new designs and trend every month and every year. Daraz.pk have a beautiful range of men fashion brands",
    price: 23,
    Color: "Multi Color",
    stock: true,
    size: "M",
    category: "mens-shirts",
    thumbnail: "https://dummyjson.com/image/i/products/51/thumbnail.jpg",
  },
  {
    id: 52,
    title: "FREE FIRE T Shirt",
    description:
      "quality and professional print - It doesn't just look high quality, it is high quality.",
    price: 10,
    Color: "Black",
    stock: true,
    size: "XL",
    category: "mens-shirts",
    thumbnail: "https://dummyjson.com/image/i/products/52/thumbnail.jpg",
  },
  {
    id: 53,
    title: "printed high quality T shirts",
    description: "Brand: vintage Apparel ,Export quality",
    price: 35,
    Color: "Black & White",
    stock: true,
    size: "L",
    category: "mens-shirts",
    thumbnail: "https://dummyjson.com/image/i/products/53/thumbnail.jpg",
  },
  {
    id: 54,
    title: "Pubg Printed Graphic T-Shirt",
    description:
      "Product Description Features: 100% Ultra soft Polyester Jersey. Vibrant & colorful printing on front. Feels soft as cotton without ever cracking",
    price: 46,
    Color: "White",
    stock: true,
    size: "M",
    category: "mens-shirts",
    thumbnail: "https://dummyjson.com/image/i/products/54/thumbnail.jpg",
  },
  {
    id: 55,
    title: "Money Heist Printed Summer T Shirts",
    description: "Fabric Jercy, Size: M & L Wear Stylish Dual Stiched",
    price: 66,
    Color: "Dark Blue",
    stock: true,
    size: "L",
    category: "mens-shirts",
    thumbnail: "https://dummyjson.com/image/i/products/55/thumbnail.jpg",
  },
  {
    id: 41,
    title: "NIGHT SUIT",
    description: "NIGHT SUIT RED MICKY MOUSE..  For Girls. Fantastic Suits.",
    price: 55,
    Color: "Red",
    stock: true,
    size: "XL",
    category: "womens-dresses",
    thumbnail: "https://dummyjson.com/image/i/products/41/thumbnail.webp",
  },
  {
    id: 42,
    title: "Stiched Kurta plus trouser",
    description:
      "FABRIC: LILEIN CHEST: 21 LENGHT: 37 TROUSER: (38) :ARABIC LILEIN",
    price: 80,
    Color: "Multi Color",
    stock: true,
    size: "M",
    category: "womens-dresses",
    thumbnail: "https://dummyjson.com/image/i/products/42/thumbnail.jpg",
  },
  {
    id: 43,
    title: "frock gold printed",
    description:
      "Ghazi fabric long frock gold printed ready to wear stitched collection (G992)",
    price: 78,
    Color: "Multi Color",
    stock: true,
    size: "L",
    category: "womens-dresses",
    thumbnail: "https://dummyjson.com/image/i/products/43/thumbnail.jpg",
  },
  {
    id: 44,
    title: "Ladies Multicolored Dress",
    description:
      "This classy shirt for women gives you a gorgeous look on everyday wear and specially for semi-casual wears.",
    price: 79,
    Color: "Black & White",
    stock: true,
    size: "XL",
    category: "womens-dresses",
    thumbnail: "https://dummyjson.com/image/i/products/44/thumbnail.jpg",
  },
  {
    id: 45,
    title: "Malai Maxi Dress",
    description:
      "Ready to wear, Unique design according to modern standard fashion, Best fitting ,Imported stuff",
    price: 50,
    Color: "Black",
    stock: true,
    size: "M",
    category: "womens-dresses",
    thumbnail: "https://dummyjson.com/image/i/products/45/thumbnail.jpg",
  },
  {
    id: 46,
    title: "women's shoes",
    description:
      "Close: Lace, Style with bottom: Increased inside, Sole Material: Rubber",
    price: 40,
    Color: "Silver",
    stock: true,
    size: "XL",
    category: "womens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/46/thumbnail.jpg",
  },
  {
    id: 47,
    title: "Sneaker shoes",
    description:
      "Synthetic Leather Casual Sneaker shoes for Women/girls Sneakers For Women",
    price: 120,
    Color: "Light Pink",
    stock: true,
    size: "L",
    category: "womens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/47/thumbnail.jpeg",
  },
  {
    id: 48,
    title: "Women Strip Heel",
    description:
      "Features: Flip-flops, Mid Heel, Comfortable, Striped Heel, Antiskid, Striped",
    price: 39,
    Color: "Multi Color",
    stock: true,
    size: "L",
    category: "womens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/48/thumbnail.jpg",
  },
  {
    id: 49,
    title: "Chappals & Shoe Ladies Metallic",
    description:
      "Womens Chappals & Shoe Ladies Metallic Tong Thong Sandal Flat Summer 2020 Maasai Sandals",
    price: 71,
    Color: "Multi Color",
    stock: true,
    size: "XL",
    category: "womens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/49/thumbnail.jpg",
  },
  {
    id: 50,
    title: "Women Shoes",
    description:
      "2020 New Arrivals Genuine Leather Fashion Trend Platform Summer Women Shoes",
    price: 36,
    Color: "Black",
    stock: true,
    size: "M",
    category: "womens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/50/thumbnail.jpg",
  },
  {
    id: 56,
    title: "Sneakers Joggers Shoes",
    description:
      "Gender: Men , Colors: Same as DisplayedCondition: 100% Brand New",
    price: 63,
    Color: "Black",
    stock: true,
    size: "L",
    category: "mens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/56/thumbnail.jpg",
  },
  {
    id: 57,
    title: "Loafers for men",
    description:
      "Men Shoes - Loafers for men - Rubber Shoes - Nylon Shoes - Shoes for men - Moccassion - Pure Nylon (Rubber) Expot Quality.",
    price: 47,
    Color: "Black",
    stock: true,
    size: "XL",
    category: "mens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/57/thumbnail.jpg",
  },
  {
    id: 58,
    title: "formal offices shoes",
    description:
      "Pattern Type: Solid, Material: PU, Toe Shape: Pointed Toe ,Outsole Material: Rubber",
    price: 57,
    Color: "Black",
    stock: true,
    size: "M",
    category: "mens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/58/thumbnail.jpg",
  },
  {
    id: 59,
    title: "Spring and summershoes",
    description:
      "Comfortable stretch cloth, lightweight body; ,rubber sole, anti-skid wear;",
    price: 19,
    Color: "Black",
    stock: true,
    size: "L",
    category: "mens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/59/thumbnail.jpg",
  },
  {
    id: 60,
    title: "Stylish Casual Jeans Shoes",
    description:
      "High Quality ,Stylish design ,Comfortable wear ,FAshion ,Durable",
    price: 58,
    Color: "Navy",
    stock: false,
    size: "M",
    category: "mens-shoes",
    thumbnail: "https://dummyjson.com/image/i/products/60/thumbnail.jpg",
  },
];
